//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doormandondemand
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buildings
    {
        public Buildings()
        {
            this.ActiveManager = new HashSet<ActiveManager>();
            this.Apartment = new HashSet<Apartment>();
            this.PendingModules = new HashSet<PendingModules>();
            this.BuildingUser = new HashSet<BuildingUser>();
            this.BuildingUserMapping = new HashSet<BuildingUserMapping>();
            this.ManagerBuilding = new HashSet<ManagerBuilding>();
            this.RepairRequestCategories = new HashSet<RepairRequestCategories>();
            this.Shipment = new HashSet<Shipment>();
            this.UserActivityLog = new HashSet<UserActivityLog>();
            this.Contractor = new HashSet<Contractor>();
            this.RepairRequest = new HashSet<RepairRequest>();
        }
    
        public int ID { get; set; }
        public string BuildingName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> NumberOfApartment { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string BuildingPhone { get; set; }
        public string Manager { get; set; }
        public string ManagersID { get; set; }
    
        public virtual ICollection<ActiveManager> ActiveManager { get; set; }
        public virtual ICollection<Apartment> Apartment { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Manager Manager1 { get; set; }
        public virtual ICollection<PendingModules> PendingModules { get; set; }
        public virtual ICollection<BuildingUser> BuildingUser { get; set; }
        public virtual ICollection<BuildingUserMapping> BuildingUserMapping { get; set; }
        public virtual ICollection<ManagerBuilding> ManagerBuilding { get; set; }
        public virtual ICollection<RepairRequestCategories> RepairRequestCategories { get; set; }
        public virtual ICollection<Shipment> Shipment { get; set; }
        public virtual ICollection<UserActivityLog> UserActivityLog { get; set; }
        public virtual ICollection<Contractor> Contractor { get; set; }
        public virtual ICollection<RepairRequest> RepairRequest { get; set; }
    }
}
