//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doormandondemand
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContact
    {
        public int ID { get; set; }
        public string First_Name_ { get; set; }
        public string Last_Name_ { get; set; }
        public string Address_ { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Phone { get; set; }
        public int ClientID { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string PhotoName { get; set; }
    }
}
