//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doormandondemand
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        public Contractor()
        {
            this.RepairRequest = new HashSet<RepairRequest>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Phone { get; set; }
        public string ContactName { get; set; }
        public string ContractPhone { get; set; }
        public string CategoryName { get; set; }
        public bool SendNewPass { get; set; }
        public int BuildingID { get; set; }
        public string Comments { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Buildings Buildings { get; set; }
        public virtual ICollection<RepairRequest> RepairRequest { get; set; }
    }
}
