//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityMonitor.Models.EntityFrameworkFL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public Apartment()
        {
            this.Tenants = new HashSet<Tenant>();
        }
    
        public int ID { get; set; }
        public string ApartmentNumber { get; set; }
        public string FloorNumber { get; set; }
        public int BuildingID { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual ICollection<Tenant> Tenants { get; set; }
    }
}
