//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityMonitor.Models.EntityFrameworkFL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Apartments = new HashSet<Apartment>();
        }
    
        public int ID { get; set; }
        public string BuildingName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> NumberOfApartment { get; set; }
        public int ClientID { get; set; }
        public string BuildingPhone { get; set; }
        public string Manager { get; set; }
    
        public virtual ICollection<Apartment> Apartments { get; set; }
        public virtual Client Client { get; set; }
    }
}
