//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityMonitor.Models.EntityFrameworkFL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Buildings = new HashSet<Buildings>();
        }
    
        public int ID { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> BuildingCount { get; set; }
    
        public virtual ICollection<Buildings> Buildings { get; set; }
    }
}
