//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityMonitor.Models.EntityFrameworkFL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfModule
    {
        public ListOfModule()
        {
            this.Module = new HashSet<Module>();
        }
    
        public int ID { get; set; }
        public string ModuleName { get; set; }
    
        public virtual ICollection<Module> Module { get; set; }
    }
}
