//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityMonitor.Models.EntityFrameworkFL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivityLog
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public int BuildingID { get; set; }
        public string Function_Performed { get; set; }
        public System.DateTime DateOfEvent { get; set; }
        public string Message { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Building Building { get; set; }
    }
}
