//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointerSecurityDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public string TrackingNumber { get; set; }
        public string Service { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
        public int ShipmentID { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
