//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointerSecurityDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public Shipment()
        {
            this.Package = new HashSet<Package>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public int aptID { get; set; }
        public string BuildingUserID { get; set; }
        public string PackageID { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<Package> Package { get; set; }
    }
}
