//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointerSecurity_Azure
{
    using System;
    using System.Collections.Generic;
    
    public partial class GanttLinkId
    {
        public int GantLinkID { get; set; }
        public string Type { get; set; }
        public int SourceTaskId { get; set; }
        public int TargerTaskId { get; set; }
    }
}
