//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointerSecurity_Azure
{
    using System;
    using System.Collections.Generic;
    
    public partial class GanttTask
    {
        public int GantTaskID { get; set; }
        public string Text { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Duration { get; set; }
        public decimal Progress { get; set; }
        public int SortOrder { get; set; }
        public string Type { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
