//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointerSecurityAzure
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingUserMapping
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public int BuildingID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Buildings Buildings { get; set; }
    }
}
