//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointerSecurityAzure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public Manager()
        {
            this.ActiveManager = new HashSet<ActiveManager>();
            this.Buildings = new HashSet<Buildings>();
            this.ManagerBuilding = new HashSet<ManagerBuilding>();
        }
    
        public string ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual ICollection<ActiveManager> ActiveManager { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<Buildings> Buildings { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual ICollection<ManagerBuilding> ManagerBuilding { get; set; }
    }
}
